### ISSUE TITLE
Add a TLS certificate

### ISSUE THREAD

**Issue by fenhl** [matthewkirby/RSLLeaderboard#13]
My browser complains when I try to visit <https://rsl.one/> because it doesn't offer an HTTPS version. You can get free certificates from <https://letsencrypt.org/> — the exact setup depends on the tech stack, but there are generally scripts that can be set up as cronjobs to automatically renew the certificates as well.

**Comment by matthewkirby** [comment]
Thanks for opening the issue. I have it in my short term todo list along
with the steps, just haven’t gotten to it yet.

**Comment by matthewkirby** [comment]
Done. I now have ssl certificates and the autorenewal set up and the http version redirecting to the https site.
